FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p static/images static/audio static/video

ENV PYTHONUNBUFFERED=1

CMD ["celery", "-A", "celery_config", "worker", "--loglevel=info"]
